import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillInstagram,
  AiFillGoogleCircle,
} from "react-icons/ai";
import image1 from "../public/images/image1.jpg";
import image2 from "../public/images/image2.jpg";
import image3 from "../public/images/image3.jpg";
import image4 from "../public/images/image4.jpg";
import image5 from "../public/images/image5.jpg";
import image6 from "../public/images/image6.jpg";
import image7 from "../public/images/image7.jpg";
import image8 from "../public/images/image8.jpg";
import image9 from "../public/images/image9.jpg";
import image10 from "../public/images/image10.jpg";
import image11 from "../public/images/image11.jpg";
import image12 from "../public/images/image12.jpg";
import image13 from "../public/images/image13.jpg";
import image14 from "../public/images/image14.jpg";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode? "dark": ""}>
      <Head>
        <title>Photographer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto px-10 md:px-20 lg:px-20 font-Poppins dark:bg-gray-900 dark:text-white">
        <section>
          {/* navigation */}
          <div className="container mx-auto py-10">
            <nav className="flex justify-between">
              <h1 className="text-xl">photography</h1>
              <div className="flex items-center gap-4">
              <BsFillMoonStarsFill className="text-2xl cursor-pointer" onClick={()=>setDarkMode(!darkMode)}/>
                  <button className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8">Resume</button>
              </div>
            </nav>
          </div>
          {/* content */}
          <div className="text-center p-4">
            <div>
              <h2 className="text-5xl text-teal-600 font-medium">
                Abdullah's Photography
              </h2>
              <h3 className="text-2xl py-2">Full-Stack Developer</h3>
              <p className="text-sm py-5 leading-8 text-gray-800 dark:text-white">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum
                quasi cupiditate ducimus debitis distinctio cumque mollitia,
                autem, aperiam maxime delectus dolores soluta, iste architecto
                adipisci! Impedit, voluptates! Unde, voluptas corporis.
              </p>
            </div>
            {/* icons */}
            <div className="flex text-5xl justify-center gap-8 text-gray-600">
              <AiFillTwitterCircle />
              <AiFillInstagram />
              <AiFillGoogleCircle />
            </div>
            <div className="relative mt-4 mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 to-gray-50 overflow-hidden">
              <Image
                src={image1}
                alt="image1"
                layout="fill"
                objectFit="cover"
              />
            </div>
          </div>
        </section>
        {/* end of header section */}
        <section className="mb-4">
          <div className="text-center px-10">
            <h3 className="text-3xl py-1">Services I offer</h3>
            <div>
            <p className="text-sm py-5 leading-8 text-gray-800 dark:text-white">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex
              corrupti voluptas officia totam modi quod, delectus tempore illo
              mollitia quam cum. Numquam consequuntur possimus omnis dicta eum
              architecto ullam exercitationem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex
              corrupti voluptas officia totam modi quod, delectus tempore illo
              mollitia quam cum. Numquam consequuntur possimus omnis dicta eum
              architecto ullam exercitationem.
            </p>            
            </div>
          </div>
          {/* cards */}
          <div className="lg:flex gap-10">
            {/* card item */}
          <div className="flex  flex-col items-center  justify-between text-center shadow-lg p-8 my-10 dark:shadow-gray-800">
            
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              class="w-12 h-12"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M17.25 6.75L22.5 12l-5.25 5.25m-10.5 0L1.5 12l5.25-5.25m7.5-3l-4.5 16.5"
              />
            </svg>
            <h3 className="text-2xl">Development</h3>
            <p className="text-xs">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit.
              Assumenda dolor eius quam? Maxime, repellat similique non id
              deleniti, repellendus blanditiis, iste explicabo cumque aut
              repudiandae cum natus. Officia, atque explicabo!
            </p>
            <h4 className="text-teal-700">Tools I Use</h4>
            <div className="flex justify-center gap-2 flex-wrap">
              <p className="text-sm font-semibold px-1 py-0 shadow-sm hover:shadow-lg">
                Shopify
              </p>
              <p className="text-sm font-semibold px-1 py-0 shadow-sm hover:shadow-lg">
                Woocommerce
              </p>
              <p className="text-sm font-semibold px-1 py-0 shadow-sm hover:shadow-lg">
                Wix
              </p>
              <p className="text-sm font-semibold  px-1 py-0 shadow-sm hover:shadow-lg">
                Laravel
              </p>
            </div>
          </div>

          {/* card item */}
          <div className="flex flex-col items-center justify-center gap-4 shadow-lg p-8 my-10 dark:shadow-gray-800">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              class="w-12 h-12"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M12 21a9.004 9.004 0 008.716-6.747M12 21a9.004 9.004 0 01-8.716-6.747M12 21c2.485 0 4.5-4.03 4.5-9S14.485 3 12 3m0 18c-2.485 0-4.5-4.03-4.5-9S9.515 3 12 3m0 0a8.997 8.997 0 017.843 4.582M12 3a8.997 8.997 0 00-7.843 4.582m15.686 0A11.953 11.953 0 0112 10.5c-2.998 0-5.74-1.1-7.843-2.918m15.686 0A8.959 8.959 0 0121 12c0 .778-.099 1.533-.284 2.253m0 0A17.919 17.919 0 0112 16.5c-3.162 0-6.133-.815-8.716-2.247m0 0A9.015 9.015 0 013 12c0-1.605.42-3.113 1.157-4.418"
              />
            </svg>
            <h3 className="text-2xl">Web</h3>
            <p className="text-xs">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit.
              Assumenda dolor eius quam? Maxime, repellat similique non id
              deleniti, repellendus blanditiis, iste explicabo cumque aut
              repudiandae cum natus. Officia, atque explicabo!
            </p>
            <h4 className="text-teal-700">Tools I Use</h4>
            <div className="flex justify-center gap-2 flex-wrap">
              <p className="text-sm font-semibold px-1 py-0 shadow-sm hover:shadow-lg">
                Shopify
              </p>
              <p className="text-sm font-semibold px-1 py-0 shadow-sm hover:shadow-lg">
                Woocommerce
              </p>
              <p className="text-sm font-semibold px-1 py-0 shadow-sm hover:shadow-lg">
                Wix
              </p>
              <p className="text-sm font-semibold  px-1 py-0 shadow-sm hover:shadow-lg">
                Laravel
              </p>
            </div>
          </div>
          {/* card item */}
          <div className="flex flex-col items-center justify-center gap-4 shadow-lg p-8 my-10 dark:shadow-gray-800">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              class="w-12 h-12"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 00-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 00-16.536-1.84M7.5 14.25L5.106 5.272M6 20.25a.75.75 0 11-1.5 0 .75.75 0 011.5 0zm12.75 0a.75.75 0 11-1.5 0 .75.75 0 011.5 0z"
              />
            </svg>
            <h3 className="text-2xl">eCommerce</h3>
            <p className="text-xs">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit.
              Assumenda dolor eius quam? Maxime, repellat similique non id
              deleniti, repellendus blanditiis, iste explicabo cumque aut
              repudiandae cum natus. Officia, atque explicabo!
            </p>
            <h4 className="text-teal-700">Tools I Use</h4>
            <div className="flex justify-center gap-2 flex-wrap">
              <p className="text-sm font-semibold px-1 py-0 shadow-sm hover:shadow-lg">
                Shopify
              </p>
              <p className="text-sm font-semibold px-1 py-0 shadow-sm hover:shadow-lg">
                Woocommerce
              </p>
              <p className="text-sm font-semibold px-1 py-0 shadow-sm hover:shadow-lg">
                Wix
              </p>
              <p className="text-sm font-semibold  px-1 py-0 shadow-sm hover:shadow-lg">
                Laravel
              </p>
            </div>
          </div>
          </div>
        </section>
        {/* portfolio */}
        <section>
           {/*header  */}
           <div>
            <h3 className="text-3xl py-1">Portfolio</h3>
              <p className="text-sm py-2 leading-8 text-gray-600 dark:text-white">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex
                corrupti voluptas officia totam modi quod, delectus tempore illo
                mollitia quam cum. Numquam consequuntur possimus omnis dicta eum
                architecto ullam exercitationem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex
                corrupti voluptas officia totam modi quod, delectus tempore illo
                mollitia quam cum. Numquam consequuntur possimus omnis dicta eum
                architecto ullam exercitationem.
              </p>
           </div>
           {/* grid */}

           <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            {/* image item */}
            <div className="basis-1/3 flex-1">
              <Image src={image1} height={"100%"} width={"100%"} 
              className="rounded-lg object-cover"
              layout="responsive" />
            </div>
            {/* image item */}
            <div className="basis-1/3 flex-1">
              <Image src={image2} height={"100%"} width={"100%"} 
              className="rounded-lg object-cover"
              layout="responsive" />
            </div>
            {/* image item */}
            <div className="basis-1/3 flex-1">
              <Image src={image3} height={"100%"} width={"100%"} 
              className="rounded-lg object-cover w-40 h-40"
              layout="responsive" />
            </div>
            {/* image item */}
            <div className="basis-1/3 flex-1">
              <Image src={image4} height={"100%"} width={"100%"} 
              className="rounded-lg object-cover"
              layout="responsive" />
            </div>
            {/* image item */}
            <div className="basis-1/3 flex-1">
              <Image src={image5} height={"100%"} width={"100%"} 
              className="rounded-lg object-cover"
              layout="responsive" />
            </div>
            {/* image item */}
            <div className="basis-1/3 flex-1">
              <Image src={image6} height={"100%"} width={"100%"} 
              className="rounded-lg object-cover"
              layout="responsive" />
            </div>
            {/* image item */}
            <div className="basis-1/3 flex-1">
              <Image src={image7} height={"100%"} width={"100%"} 
              className="rounded-lg object-cover"
              layout="responsive" />
            </div>
            {/* image item */}
            <div className="basis-1/3 flex-1">
              <Image src={image8} height={"100%"} width={"100%"} 
              className="rounded-lg object-cover"
              layout="responsive" />
            </div>
            {/* image item */}
            <div className="basis-1/3 flex-1">
              <Image src={image9} height={"100%"} width={"100%"} 
              className="rounded-lg object-cover"
              layout="responsive" />
            </div>
            {/* image item */}
            <div className="basis-1/3 flex-1">
              <Image src={image10} height={"100%"} width={"100%"} 
              className="rounded-lg object-cover"
              layout="responsive" />
            </div>
            {/* image item */}
            <div className="basis-1/3 flex-1">
              <Image src={image11} height={"100%"} width={"100%"} 
              className="rounded-lg object-cover"
              layout="responsive" />
            </div>
            {/* image item */}
            <div className="basis-1/3 flex-1">
              <Image src={image12} height={"100%"} width={"100%"} 
              className="rounded-lg object-cover"
              layout="responsive" />
            </div>
            {/* image item */}
            <div className="basis-1/3 flex-1">
              <Image src={image13} height={"100%"} width={"100%"} 
              className="rounded-lg object-cover"
              layout="responsive" />
            </div>
            {/* image item */}
            <div className="basis-1/3 flex-1">
              <Image src={image14} height={"100%"} width={"100%"} 
              className="rounded-lg object-cover"
              layout="responsive" />
            </div>
           </div>

        </section>
      </main>
    </div>
  );
}
